// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace UploadFile
{
    public partial class Invoices
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public DateTime Date { get; set; }
        public decimal Value { get; set; }
        public byte[] Attachment { get; set; }
    }
}